SET GLOBAL local_infile=1;
USE PokeFind;
LOAD DATA LOCAL INFILE 'C:/Temp/pokemon.csv' INTO TABLE pokemon FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'C:/Temp/attack.csv' INTO TABLE attack FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'C:/Temp/weakness.csv' INTO TABLE weakness FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'C:/Temp/price.csv' INTO TABLE price FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';